In [66]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

# Analysis Pipeline Refined

In [87]:
# Load data 
df = pd.read_csv('/Users/evanlewis/data301/Project/project-group53-project/data/raw/PRWI_Data.csv')
df

,Admin_Unit_Code,Sub_Unit_Code,Site_Name,Plot_Name,Location_Type,Year,Date,Start_Time,End_Time,Observer,...,NPSTaxonCode,AOU_Code,PIF_Watchlist_Status,Regional_Stewardship_Status,Temperature,Humidity,Sky,Wind,Disturbance,Initial_Three_Min_Cnt
0,PRWI,NaN,PRWI 2,PRWI-0097,Forest,2007,2007-05-29,6:27,6:46,Desiree Narango,...,85846.0,EAWP,False,True,18.5,85.0,Partly Cloudy,Calm (< 1 mph) smoke rises vertically,Slight effect on count,False
1,PRWI,NaN,PRWI 2,PRWI-0097,Forest,2007,2007-05-29,6:27,6:46,Desiree Narango,...,93587.0,REVI,False,False,18.5,85.0,Partly Cloudy,Calm (< 1 mph) smoke rises vertically,Slight effect on count,False
2,PRWI,NaN,PRWI 2,PRWI-0097,Forest,2007,2007-05-29,6:27,6:46,Desiree Narango,...,95300.0,AMGO,False,False,18.5,85.0,Partly Cloudy,Calm (< 1 mph) smoke rises vertically,Slight effect on count,False
3,PRWI,NaN,PRWI 2,PRWI-0097,Forest,2007,2007-05-29,6:27,6:46,Desiree Narango,...,92689.0,OVEN,False,False,18.5,85.0,Partly Cloudy,Calm (< 1 mph) smoke rises vertically,Slight effect on count,False
4,PRWI,NaN,PRWI 2,PRWI-0097,Forest,2007,2007-05-29,6:27,6:46,Desiree Narango,...,266957.0,ETTI,False,False,18.5,85.0,Partly Cloudy,Calm (< 1 mph) smoke rises vertically,Slight effect on count,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29106,PRWI,NaN,PRWI 22,PRWI-0728,Forest,2017,2017-07-16,6:32,6:42,Ryan Trenkamp,...,266957.0,ETTI,False,False,21.0,74.0,Clear or Few Clouds,Light breeze (4-7 mph) wind felt on face,Moderate effect on count,False
29107,PRWI,NaN,PRWI 22,PRWI-0728,Forest,2017,2017-07-16,6:32,6:42,Ryan Trenkamp,...,85739.0,HAWO,False,False,21.0,74.0,Clear or Few Clouds,Light breeze (4-7 mph) wind felt on face,Moderate effect on count,False
29108,PRWI,NaN,PRWI 22,PRWI-0728,Forest,2017,2017-07-16,6:32,6:42,Ryan Trenkamp,...,93587.0,REVI,False,False,21.0,74.0,Clear or Few Clouds,Light breeze (4-7 mph) wind felt on face,Moderate effect on count,True
29109,PRWI,NaN,PRWI 22,PRWI-0728,Forest,2017,2017-07-16,6:32,6:42,Ryan Trenkamp,...,87136.0,AMRO,False,False,21.0,74.0,Clear or Few Clouds,Light breeze (4-7 mph) wind felt on face,Moderate effect on count,True
29110,PRWI,NaN,PRWI 22,PRWI-0728,Forest,2017,2017-07-16,6:32,6:42,Ryan Trenkamp,...,266957.0,ETTI,False,False,21.0,74.0,Clear or Few Clouds,Light breeze (4-7 mph) wind felt on face,Moderate effect on count,False

In [88]:
# Removing unneeded columns so that the dataframe only has values I will use 
lbl = ['Admin_Unit_Code', 'Sub_Unit_Code', 'Plot_Name', 'Location_Type', 'Date', 'Start_Time', 'End_Time', 'Observer', "Visit", 'NPSTaxonCode', "AOU_Code", 'PIF_Watchlist_Status', 'Regional_Stewardship_Status', 'Humidity', 'Sky', 'Wind', 'Initial_Three_Min_Cnt','Interval_Length','ID_Method','Distance','Flyover_Observed', 'Sex', 'Scientific_Name', 'AcceptedTSN','Disturbance']
df = df.drop(labels = lbl, axis = 1)
df

      Site_Name  Year              Common_Name  Temperature
0        PRWI 2  2007       Eastern Wood-Pewee         18.5
1        PRWI 2  2007           Red-eyed Vireo         18.5
2        PRWI 2  2007       American Goldfinch         18.5
3        PRWI 2  2007                 Ovenbird         18.5
4        PRWI 2  2007  Eastern Tufted Titmouse         18.5
...         ...   ...                      ...          ...
29106   PRWI 22  2017  Eastern Tufted Titmouse         21.0
29107   PRWI 22  2017         Hairy Woodpecker         21.0
29108   PRWI 22  2017           Red-eyed Vireo         21.0
29109   PRWI 22  2017           American Robin         21.0
29110   PRWI 22  2017  Eastern Tufted Titmouse         21.0

[29111 rows x 4 columns]

In [89]:
#Renaming columns
df = df.rename(columns={'Site_Name':'Site','Common_Name':'Species'})
df

          Site  Year                  Species  Temperature
0       PRWI 2  2007       Eastern Wood-Pewee         18.5
1       PRWI 2  2007           Red-eyed Vireo         18.5
2       PRWI 2  2007       American Goldfinch         18.5
3       PRWI 2  2007                 Ovenbird         18.5
4       PRWI 2  2007  Eastern Tufted Titmouse         18.5
...        ...   ...                      ...          ...
29106  PRWI 22  2017  Eastern Tufted Titmouse         21.0
29107  PRWI 22  2017         Hairy Woodpecker         21.0
29108  PRWI 22  2017           Red-eyed Vireo         21.0
29109  PRWI 22  2017           American Robin         21.0
29110  PRWI 22  2017  Eastern Tufted Titmouse         21.0

[29111 rows x 4 columns]

In [91]:
# Making a new column that aggregates temperatures into ranges
bins = [0, 15, 20, 25, 35, np.inf]
names = ['<15', '15-20', '20-25', '25-35', '35+']

df['Temperature_Class'] = pd.cut(df['Temperature'], bins, labels=names)

df

          Site  Year                  Species  Temperature Temperature_Class
0       PRWI 2  2007       Eastern Wood-Pewee         18.5             15-20
1       PRWI 2  2007           Red-eyed Vireo         18.5             15-20
2       PRWI 2  2007       American Goldfinch         18.5             15-20
3       PRWI 2  2007                 Ovenbird         18.5             15-20
4       PRWI 2  2007  Eastern Tufted Titmouse         18.5             15-20
...        ...   ...                      ...          ...               ...
29106  PRWI 22  2017  Eastern Tufted Titmouse         21.0             20-25
29107  PRWI 22  2017         Hairy Woodpecker         21.0             20-25
29108  PRWI 22  2017           Red-eyed Vireo         21.0             20-25
29109  PRWI 22  2017           American Robin         21.0             20-25
29110  PRWI 22  2017  Eastern Tufted Titmouse         21.0             20-25

[29111 rows x 5 columns]

## That's it for the pipeline, my data is ready for analysis.